language: objective-c
osx_image: xcode9
xcode_workspace: demo/demo.xcworkspace
xcode_scheme: demo
script:
- echo "release to framework_${TRAVIS_TAG}.zip - $TRAVIS_TAG"
- mkdir -p framework/static
- wget https://github.com/ksvc/KSYLive_iOS/releases/download/v2.0.0/staticGPUImage.zip
- unzip -q staticGPUImage.zip -d framework/static/
- cd releaseFramework
- "./release-KSYMediaEditor.sh"
- cd ../
- zip -q --symlinks -r framework_${TRAVIS_TAG}.zip framework/*
- rm -rf framework/static/*
- wget https://github.com/ksvc/KSYLive_iOS/releases/download/v2.0.0/dynamicGPUImage.zip
- unzip -q dynamicGPUImage.zip -d framework/dynamic/
- cd releaseFramework
- "./release-KSYMediaEditor.sh dy"
- cd ../
- zip -q --symlinks -r framework_dy_${TRAVIS_TAG}.zip framework/*
deploy:
  provider: releases
  api_key:
    secure: whHVbNgbMgk8rXFUeOZtjQmD9T5QDRcuAnL5Z/eW03u+V8IH0JC0kj4yr5uYDmKmBwzXj6j6ji/tywNUTz9pPTsQ4ZglAkDW1STvi6xUvQqXopP0HazrshYic0vxFTFcw4L7MF0X7iK+lyV+vduV/9IVv3ouW17OXB/zyDKHo1zlcHzkNspPG8ZvZX43kiqHWVR4m8IWXwUrM5oA96N+K/S0NCi7b3Pk8osnCmYN5baPnQIp63PfuYryCODWCotnZY9wG2M1piLcM3e2IbfFUTxEAt6osiD0gEOryMV2/YqxTyg0HqGcF0VVyQwsGv+kZLlksx2+obG6O+5IKpS6nX/Lp1g1HdiSZhCpGyqaDGp2xlhquBP2si7SFP4UN0EMngv8sN3oEainB4aIU2eShiVVwFTFxozSJGa9LKjI2mOOnzrBLr9+7TBSp7cKu2h9Ss2TsLsGR8GjgyLVos2D9Pp4NR4Ow2z7T8c+mEg3sKrSzLD4dvRIpCjDg6qjdxmPZ/zkDXpYRdf8oUKMmymTq/lg4cShiio1ityjNmQdmXB4VKnw0cbgM3SM2bYYfirkSHKEGah4zAIuutQbLwviQ4dPgKmZwxLbU7GGmTZIBbZbfEv3Hq8p0NFGCl3HKiWDz4nsBVFAIZt4fcurkVS2SM5N99RZefM4hjyJF2LC+ys=
  file: 
    - framework_${TRAVIS_TAG}.zip
    - framework_dy_${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: ksvc/KSYMediaEditorKit_iOS
    tags: true
